#!/usr/bin/env python3
"""
Train a road surface classifier from labeled accelerometer data.

Reads training_data.csv (generated by generate_training_data.py),
computes 2-second sliding window features, trains a DecisionTreeClassifier,
and exports the learned thresholds to surface_model.json so the Node.js
backend can classify surfaces without any Python dependency at runtime.

Usage:
  pip install scikit-learn pandas numpy
  python3 ml/train_surface_classifier.py
"""

import csv
import json
import math
import os
import statistics

DATA_PATH  = os.path.join(os.path.dirname(__file__), "training_data.csv")
MODEL_PATH = os.path.join(os.path.dirname(__file__), "surface_model.json")

WINDOW_SAMPLES = 40   # 2 seconds at 20 Hz
STRIDE_SAMPLES = 10   # 0.5 s stride → 4 windows per second

SURFACE_LABELS = ["smooth_asphalt", "rough_asphalt", "cobblestone", "gravel"]


# ─── Feature extraction (same logic runs in JS for real-time inference) ───────

def extract_features(window_vert):
    """
    Compute 5 scalar features from a window of vert_accel_ms2 values.
    Returns dict matching the JS implementation in surfaceClassifier.js.
    """
    n = len(window_vert)
    mean_v = sum(window_vert) / n
    variance = sum((v - mean_v) ** 2 for v in window_vert) / n
    roughness = math.sqrt(variance)                       # std of vert_accel

    abs_vals = [abs(v) for v in window_vert]
    mean_abs = sum(abs_vals) / n                          # mean |vert_accel|
    max_abs  = max(abs_vals)                              # max |vert_accel|

    deltas = [abs(window_vert[i] - window_vert[i-1]) for i in range(1, n)]
    mean_delta = sum(deltas) / len(deltas) if deltas else 0.0  # mean |Δvert|

    # high-frequency energy: fraction of deltas above 1 m/s² (cobblestone signature)
    hf_rate = sum(1 for d in deltas if d > 1.0) / len(deltas) if deltas else 0.0

    return {
        "roughness": roughness,
        "mean_abs":  mean_abs,
        "max_abs":   max_abs,
        "mean_delta": mean_delta,
        "hf_rate":   hf_rate,
    }


# ─── Load data ────────────────────────────────────────────────────────────────

def load_data():
    rows = []
    with open(DATA_PATH, newline="") as f:
        for r in csv.DictReader(f):
            rows.append({
                "session":  r["session_id"],
                "surface":  r["surface_type"],
                "vert":     float(r["vert_accel_ms2"]),
            })
    return rows


# ─── Build windowed dataset ───────────────────────────────────────────────────

def build_windows(rows):
    # Group rows by session to avoid window bleed across sessions
    sessions = {}
    for r in rows:
        sessions.setdefault(r["session"], []).append(r)

    X, y = [], []
    for session_rows in sessions.values():
        verts = [r["vert"] for r in session_rows]
        label = session_rows[0]["surface"]  # whole session has same surface
        for start in range(0, len(verts) - WINDOW_SAMPLES, STRIDE_SAMPLES):
            window = verts[start : start + WINDOW_SAMPLES]
            feats = extract_features(window)
            X.append(feats)
            y.append(label)
    return X, y


# ─── Train classifier using sklearn DecisionTree ──────────────────────────────

def train(X, y):
    try:
        from sklearn.tree import DecisionTreeClassifier
        from sklearn.model_selection import cross_val_score
        import numpy as np

        feature_names = ["roughness", "mean_abs", "max_abs", "mean_delta", "hf_rate"]
        X_arr = np.array([[f[k] for k in feature_names] for f in X])

        clf = DecisionTreeClassifier(max_depth=4, min_samples_leaf=50, random_state=42)
        scores = cross_val_score(clf, X_arr, y, cv=5, scoring="accuracy")
        clf.fit(X_arr, y)

        print(f"  Cross-val accuracy: {scores.mean():.3f} ± {scores.std():.3f}")
        print(f"  Class distribution: { {l: y.count(l) for l in set(y)} }")

        # Extract per-class feature statistics for the fallback threshold approach
        return clf, feature_names, X_arr, y

    except ImportError:
        print("  scikit-learn not installed — falling back to percentile thresholds")
        return None, None, None, y


# ─── Compute percentile-based thresholds (fallback when sklearn unavailable) ──

def compute_thresholds(X, y):
    """
    For each surface class compute the mean roughness.
    Then derive class boundaries as midpoints between adjacent class means.
    Returns ordered list of (threshold, label) pairs for a 1D classifier.
    """
    by_class = {}
    for feats, label in zip(X, y):
        by_class.setdefault(label, []).append(feats["roughness"])

    means = {k: statistics.mean(v) for k, v in by_class.items()}
    print(f"  Mean roughness per class: {means}")

    # Sort classes by mean roughness
    ordered = sorted(means.items(), key=lambda kv: kv[1])
    thresholds = []
    for i in range(len(ordered) - 1):
        mid = (ordered[i][1] + ordered[i + 1][1]) / 2
        thresholds.append({"max_roughness": round(mid, 4), "label": ordered[i][0]})
    thresholds.append({"max_roughness": 9999, "label": ordered[-1][0]})
    return thresholds


# ─── Serialize sklearn tree to portable JSON rules ───────────────────────────

def tree_to_rules(clf, feature_names, classes):
    """Recursively convert a fitted DecisionTree into a nested JSON rule dict."""
    tree = clf.tree_

    def node_to_dict(node_id):
        if tree.children_left[node_id] == -1:  # leaf
            class_idx = tree.value[node_id][0].argmax()
            return {"label": classes[class_idx]}
        feat  = feature_names[tree.feature[node_id]]
        thresh = round(float(tree.threshold[node_id]), 6)
        return {
            "feature":   feat,
            "threshold": thresh,
            "left":  node_to_dict(tree.children_left[node_id]),   # <= threshold
            "right": node_to_dict(tree.children_right[node_id]),  # >  threshold
        }

    return node_to_dict(0)


# ─── Build model JSON ─────────────────────────────────────────────────────────

def build_model_json(X, y, clf=None, feature_names=None):
    # Per-class stats for reference
    class_stats = {
        k: {
            "mean_roughness": round(statistics.mean([f["roughness"] for f, l in zip(X, y) if l == k]), 4),
            "mean_hf_rate":   round(statistics.mean([f["hf_rate"]   for f, l in zip(X, y) if l == k]), 4),
        }
        for k in SURFACE_LABELS if k in set(y)
    }

    model = {
        "version": 2,
        "trained_at": "2026-06-21",
        "window_samples": WINDOW_SAMPLES,
        "features": ["roughness", "mean_abs", "max_abs", "mean_delta", "hf_rate"],
        "class_stats": class_stats,
    }

    if clf is not None and feature_names is not None:
        model["tree"] = tree_to_rules(clf, feature_names, list(clf.classes_))
        model["use_tree"] = True
    else:
        # Fallback: simple 1D roughness thresholds
        model["thresholds"] = compute_thresholds(X, y)
        model["use_tree"] = False

    return model


# ─── Evaluate and print confusion summary ─────────────────────────────────────

def evaluate(model_json, X, y):
    use_tree = model_json.get("use_tree", False)

    def walk_tree(node, feats):
        if "label" in node:
            return node["label"]
        val = feats[node["feature"]]
        return walk_tree(node["left"] if val <= node["threshold"] else node["right"], feats)

    def predict_threshold(feats):
        thresholds = model_json["thresholds"]
        for t in thresholds:
            if feats["roughness"] <= t["max_roughness"]:
                return t["label"]
        return thresholds[-1]["label"]

    def predict(feats):
        if use_tree:
            return walk_tree(model_json["tree"], feats)
        return predict_threshold(feats)

    correct = sum(1 for feats, label in zip(X, y) if predict(feats) == label)
    acc = correct / len(y)
    print(f"  Train accuracy: {acc:.3f}  ({correct}/{len(y)} windows)")

    # Per-class accuracy
    by_class = {}
    for feats, label in zip(X, y):
        pred = predict(feats)
        by_class.setdefault(label, {"total": 0, "correct": 0})
        by_class[label]["total"] += 1
        if pred == label:
            by_class[label]["correct"] += 1
    for cls, counts in sorted(by_class.items()):
        print(f"    {cls:20s}  {counts['correct']:4d}/{counts['total']:4d}  "
              f"({100*counts['correct']/counts['total']:.0f}%)")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print(f"\nLoading {DATA_PATH} ...")
    rows = load_data()
    print(f"  {len(rows):,} samples loaded")

    print("\nBuilding windows ...")
    X, y = build_windows(rows)
    print(f"  {len(X):,} windows  ({WINDOW_SAMPLES} samples each, stride {STRIDE_SAMPLES})")

    print("\nTraining decision tree ...")
    clf, feature_names, X_arr, y_list = train(X, y)

    model = build_model_json(X, y, clf, feature_names)

    print("\nEvaluating classifier ...")
    evaluate(model, X, y)

    with open(MODEL_PATH, "w") as f:
        json.dump(model, f, indent=2)
    print(f"\nModel written to {MODEL_PATH}")
    print(json.dumps(model, indent=2))


if __name__ == "__main__":
    main()
